In [1]:
# python list
L1 = [1,3.14,5,True,'toy']
L1

[1, 3.14, 5, True, 'toy']

In [4]:
# show the type of list's element 
print([type(ii) for ii in L1])

[<class 'int'>, <class 'float'>, <class 'int'>, <class 'bool'>, <class 'str'>]


In [6]:
# Numpy ndarray
import numpy as np 

In [7]:
# create new array 
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [8]:
# assign data type
np.array([1,3,5,7,9],dtype='float16')

array([1., 3., 5., 7., 9.], dtype=float16)

In [10]:
# assign multi-dimonsions 
np.array([[1,3],[2,4]])

array([[1, 3],
       [2, 4]])

In [11]:
# list can be converted to np type
L2 = [1,3,5,7,8]
np.array(L2)

array([1, 3, 5, 7, 8])

In [12]:
np.identity?

Signature: np.identity(n, dtype=None, *, like=None)
Docstring:
Return the identity array.

The identity array is a square array with ones on
the main diagonal.

Parameters
----------
n : int
    Number of rows (and columns) in `n` x `n` output.
dtype : data-type, optional
    Data-type of the output.  Defaults to ``float``.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    `n` x `n` array with its main diagonal set to one,
    and all other elements 0.

Examples
--------
>>> np.identity(3)
array([[1.,  0.,  0.],

In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array o

In [19]:
np.zeros((2,3),dtype = float)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.full((2,3),1.234)

array([[1.234, 1.234, 1.234],
       [1.234, 1.234, 1.234]])

In [24]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [27]:
np.linspace(1,7,4)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
# random float
np.random.random((2,3))

array([[0.03822331, 0.69791045, 0.38899907],
       [0.24980878, 0.12306969, 0.4188252 ]])

In [38]:
# random int
np.random.randint(0,100,(2,3))

array([[13, 33, 73],
       [78, 98, 35]])

In [40]:
# gaussian distribution
# u = 1.0  std = 0.25
np.random.normal(1.0,0.25,(3,3))

array([[1.24592837, 0.62204029, 0.84391431],
       [0.84639634, 0.51584415, 1.38006837],
       [0.84708615, 0.96784787, 1.31231511]])

In [41]:
# random data in mem
np.empty((2,3))

array([[0.03822331, 0.69791045, 0.38899907],
       [0.24980878, 0.12306969, 0.4188252 ]])

In [46]:
n1 = np.random.random((2,3,4))
# dimension size 
print(n1.ndim)
# shape
print(n1.shape)
# element size 
print(n1.size)
# element size 
print(n1.itemsize,' bytes')

3
(2, 3, 4)
24
8  bytes


In [48]:
n2=np.random.random((2,3))
print(n2)
# negative sequence
print(n2[1,-2])

[[0.77641729 0.58555505 0.98458713]
 [0.88637953 0.36564535 0.27952945]]
0.36564535399113707


In [53]:
# slice [:::] = [start : stop : step]
n3 = np.arange(20)
print(n3)
# from 0 to 2
print(n3[:2])
# from 2 to last 
print(n3[2:])
# from 2 to last ,gap = 2
print(n3[2::2])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14 16 18]


In [65]:
n4 = np.array([range(i*5,i*5+5) for i in range(5)])
print(n4)
print('slice is :')
n5 = n4[1:3,1:]
print(n5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
slice is :
[[ 6  7  8  9]
 [11 12 13 14]]


In [68]:
# slice will change the father element
n5[1,3] = 0
print('n5 is :\n',n5)
print('n4 is :\n',n4)

n5 is :
 [[ 6  7  8  9]
 [11 12 13  0]]
n4 is :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [69]:
# use copy()
n6 = n4[1:3,1:].copy()
n6[1,2]  = 0
print('n6 is : \n',n6)
print('n4 is : \n',n4)f

n6 is : 
 [[ 6  7  8  9]
 [11 12  0  0]]
n4 is : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [73]:
# reshape 
n7 = np.array([range(i*4,i*4+4) for i in range(4)])
n8 = n4.reshape((2,8))
print(n7)
print(n8)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [81]:
# joint the part
n9 = np.array([[2,3,4],[5,6,7]])
n10 = np.array([[10,11,12]])
n11 = np.array([[99],[100]])
print('n9 + n10 is:\n',np.concatenate([n9,n10],axis = 0))
print('n9 + n11 is:\n',np.concatenate([n9,n11],axis = 1))

n9 + n10 is:
 [[ 2  3  4]
 [ 5  6  7]
 [10 11 12]]
n9 + n11 is:
 [[  2   3   4  99]
 [  5   6   7 100]]


In [82]:
# vstack 
print('vstack demo: \n',np.vstack([n9,n10]))
# hstack 
print('hstack demo: \n',np.hstack([n9,n11]))

vstack demo: 
 [[ 2  3  4]
 [ 5  6  7]
 [10 11 12]]
hstack demo: 
 [[  2   3   4  99]
 [  5   6   7 100]]


In [83]:
# vsplit 
print('vsplit demo \n',np.vsplit(n9,[1]))
# hsplit 
print('hsplit demo \n',np.hsplit(n9,[1,2]))

vsplit demo 
 [array([[2, 3, 4]]), array([[5, 6, 7]])]
hsplit demo 
 [array([[2],
       [5]]), array([[3],
       [6]]), array([[4],
       [7]])]


In [86]:
n12 = np.arange(9).reshape((3,3))
print(2**n12)

[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


In [89]:
# reduce
n13 = np.arange(1,6)
print(np.add.accumulate(n13))
print(np.multiply.accumulate(n13))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [94]:
n14 = np.random.random(5)
print('n14 is :\n',n14)
print('sum is :\n',n14.sum())
print('prod is :\n',n14.prod())
print('mean is :\n',n14.mean())
print('std is :\n',n14.std())
print('max is :\n',n14.max())
print('min is :\n',n14.min())

n14 is :
 [0.0567776  0.72840423 0.8343837  0.46498036 0.0930137 ]
sum is :
 2.177559595763483
prod is :
 0.001492439879048927
mean is :
 0.4355119191526966
std is :
 0.3182758895811017
max is :
 0.8343837010360657
min is :
 0.05677760247434538
